Repository JUDA-Hrmi/JUDA, pull requests merged in 2024-04, with the labels that each got.

#169 Cloud function/javascript
  Cloud_Function/index.js
  Cloud_Function/main.py
Labels: 수정

#170 [Refactoring] - 에러 수정
  JUDA_iOS/JUDA.xcodeproj/project.pbxproj
  JUDA_iOS/JUDA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  JUDA_iOS/JUDA.xcodeproj/xcshareddata/xcschemes/JUDA.xcscheme
  JUDA_iOS/JUDA/Info.plist
  JUDA_iOS/JUDA/Model/User.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA_iOS/JUDA/View/LogIn/ProfileSettingView.swift
  JUDA_iOS/JUDA/View/Main/MainView.swift
  JUDA_iOS/JUDA/View/Mypage/AuthenticatedMypageView.swift
  JUDA_iOS/JUDA/View/Mypage/MyPageView.swift
  JUDA_iOS/JUDA/View/Mypage/MypageDetail/AlarmStoreView.swift
  JUDA_iOS/JUDA/View/Mypage/MypageDetail/UserProfileView.swift
  JUDA_iOS/JUDA/View/Mypage/SettingView.swift
  JUDA_iOS/JUDA/View/Mypage/UnauthenticatedMypageView.swift
  JUDA_iOS/JUDA/ViewModel/App/AppViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Auth/AuthViewModel.swift
Labels: 버그, 수정

#172 [Refactoring] 뷰 연결 후 에러 수정 중 #166
  JUDA_iOS/JUDA.xcodeproj/project.pbxproj
  JUDA_iOS/JUDA.xcodeproj/xcshareddata/xcschemes/JUDA.xcscheme
  JUDA_iOS/JUDA/Resource/Components/CustomDialog.swift
  JUDA_iOS/JUDA/Resource/Components/DrinkGridCell.swift
  JUDA_iOS/JUDA/Resource/Components/DrinkListCell.swift
  JUDA_iOS/JUDA/Resource/Components/PostCell.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkDetail/DrinkDetailView.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkDetail/TaggedTrendingPosts.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA_iOS/JUDA/View/Main/MainView.swift
  JUDA_iOS/JUDA/View/Main/PostTopView.swift
  JUDA_iOS/JUDA/View/Mypage/MypageDetail/AlarmStoreListCell.swift
  JUDA_iOS/JUDA/View/Mypage/MypageDetail/AlarmStoreView.swift
  JUDA_iOS/JUDA/View/Mypage/MypageDetail/ChangeUserNameView.swift
  JUDA_iOS/JUDA/View/Mypage/NavigationProfileView.swift
  JUDA_iOS/JUDA/View/Posts/NavigationPostsView.swift
  JUDA_iOS/JUDA/View/Posts/PostDetail/PostDetailView.swift
  JUDA_iOS/JUDA/View/Posts/PostDetail/PostInfo.swift
  JUDA_iOS/JUDA/View/Posts/PostGrid.swift
  JUDA_iOS/JUDA/View/Posts/PostsView.swift
  JUDA_iOS/JUDA/View/Record/AddTagView.swift
  JUDA_iOS/JUDA/View/Record/DrinkTagScroll.swift
  JUDA_iOS/JUDA/View/Record/SearchTagView.swift
  JUDA_iOS/JUDA/ViewModel/Auth/AuthViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Record/RecordViewModel.swift
  JUDA_iOS/JUDA/ViewModel/User/FirebaseUserService.swift
  JUDA_iOS/JUDA/ViewModel/User/UserViewModel.swift
Labels: 수정

#175 [Refactoring] MyPageView 에서 Navigation 이동 시, UI 오류 & Drink 에서 초기 20개 이후, 추가 데이터 불러올 때 화면 깨짐
  JUDA_iOS/JUDA.xcodeproj/project.pbxproj
  JUDA_iOS/JUDA.xcodeproj/xcshareddata/xcschemes/JUDA.xcscheme
  JUDA_iOS/JUDA/Info.plist
  JUDA_iOS/JUDA/JUDA.entitlements
  JUDA_iOS/JUDA/Resource/Components/ErrorPageView.swift
  JUDA_iOS/JUDA/View/ContentView/ContentView.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkDetail/DrinkDetailView.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkInfoGrid.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA_iOS/JUDA/View/Liked/LikedView.swift
  JUDA_iOS/JUDA/View/LogIn/LogInView.swift
  JUDA_iOS/JUDA/View/LogIn/TermsAndVerificationView.swift
  JUDA_iOS/JUDA/View/Main/MainView.swift
  JUDA_iOS/JUDA/View/Mypage/MyPageView.swift
  JUDA_iOS/JUDA/View/Mypage/SettingDetail/NoticeView.swift
  JUDA_iOS/JUDA/View/Mypage/SettingView.swift
  JUDA_iOS/JUDA/View/Mypage/UnauthenticatedMypageView.swift
  JUDA_iOS/JUDA/View/Posts/PostDetail/PostDetailView.swift
  JUDA_iOS/JUDA/View/Posts/PostsView.swift
  JUDA_iOS/JUDA/ViewModel/Auth/AuthViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Drink/DrinkViewModel.swift
Labels: 버그, 디자인, 수정, 🥑 창준

#177 Refactoring/post search
  JUDA_iOS/JUDA.xcodeproj/project.pbxproj
  JUDA_iOS/JUDA.xcodeproj/xcshareddata/xcschemes/JUDA.xcscheme
  JUDA_iOS/JUDA/Resource/Constants.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA_iOS/JUDA/View/Main/MainView.swift
  JUDA_iOS/JUDA/View/Mypage/AuthenticatedMypageView.swift
  JUDA_iOS/JUDA/View/Mypage/NavigationProfileView.swift
  JUDA_iOS/JUDA/View/Posts/NavigationPostsView.swift
  JUDA_iOS/JUDA/View/Posts/PostDetail/PostDetailView.swift
  JUDA_iOS/JUDA/View/Posts/PostDetail/PostTags.swift
  JUDA_iOS/JUDA/View/Posts/PostGrid.swift
  JUDA_iOS/JUDA/View/Posts/PostSearchList.swift
  JUDA_iOS/JUDA/View/Posts/PostsView.swift
  JUDA_iOS/JUDA/ViewModel/App/NavigationRouter.swift
  JUDA_iOS/JUDA/ViewModel/Posts/PostViewModel.swift
Labels: 버그, 기능, 데이터, 수정

#179 [Refactoring] NavigationPostsView 탭뷰, LoginDialog(CustomDialog) 오류 해결 #178
  JUDA_iOS/JUDA.xcodeproj/project.pbxproj
  JUDA_iOS/JUDA/Resource/Components/CustomDialog.swift
  JUDA_iOS/JUDA/Resource/UINavigationController +.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkDetail/DrinkDetailView.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA_iOS/JUDA/View/Posts/NavigationPostsView.swift
Labels: 버그, 디자인, 수정
