Repository JUDA-Hrmi/JUDA, pull requests merged in 2024-01, with the labels that each got.

#12 [Add] DrinkSelectHorizontalScrollBar 작성 #9
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/FinalHrmiProjectsApp.swift
  FinalHrmiProjects/Resource/Components/DrinkSelectHorizontalScrollBar.swift
Labels: 디자인, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#18 [Add] PostCell UI 구현 #4 / CustomTextSegment UI 구현 #13
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomTextSegment.swift
  FinalHrmiProjects/Resource/Components/PostCell.swift
Labels: 디자인, 🥑 창준, 🫧 세희, :tiger: 인선, 🦎 대홍

#10 [Add] DrinkListCell 작성
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Assets.xcassets/canuca.imageset/Contents.json
  FinalHrmiProjects/Assets.xcassets/canuca.imageset/canuca.jpg
  FinalHrmiProjects/Assets.xcassets/canuca.imageset/제목 4.png
  FinalHrmiProjects/Resource/Components/DrinkListCell.swift
Labels: 디자인, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#11 [Add] DrinkGridCell 작성
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Colors.xcassets/MainBlack.colorset/Contents.json
  FinalHrmiProjects/Resource/Components/DrinkGridCell.swift
Labels: 디자인, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#21 [Add] CustomDivider 추가 #20
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomDivider.swift
Labels: 디자인, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#24 [Add] DrinkInfoView에서 사용하는 [그리드/리스트 --- 인기/최신] 세그먼트 제작 #17
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects.xcodeproj/project.xcworkspace/xcuserdata/hongsehui.xcuserdatad/UserInterfaceState.xcuserstate
  FinalHrmiProjects/Assets.xcassets/CustomSymbol/Contents.json
  FinalHrmiProjects/Assets.xcassets/CustomSymbol/arrow.style.symbolset/Contents.json
  FinalHrmiProjects/Assets.xcassets/CustomSymbol/arrow.style.symbolset/arrow.down.svg
  FinalHrmiProjects/Assets.xcassets/CustomSymbol/grid.style.symbolset/Contents.json
  FinalHrmiProjects/Assets.xcassets/CustomSymbol/grid.style.symbolset/square.grid.2x2.fill.svg
  FinalHrmiProjects/Assets.xcassets/CustomSymbol/list.style.symbolset/Contents.json
  FinalHrmiProjects/Assets.xcassets/CustomSymbol/list.style.symbolset/list.bullets.svg
  FinalHrmiProjects/Resource/Components/CustomBottomSheet.swift
  FinalHrmiProjects/Resource/Components/DrinkInfoSegment.swift
  FinalHrmiProjects/View/DrinkInfo/EnabledBottomSheetView.swift
Labels: 디자인, 🥑 창준, 👻 민재, :tiger: 인선, 🦎 대홍

#38 [Add] Theme 파일 추가 및 시스템에 따른 sheet 색상 변경 #35
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects.xcodeproj/project.xcworkspace/xcuserdata/hongsehui.xcuserdatad/UserInterfaceState.xcuserstate
  FinalHrmiProjects/Resource/Components/CustomBottomSheet.swift
  FinalHrmiProjects/Resource/Theme.swift
  FinalHrmiProjects/View/DrinkInfo/EnabledBottomSheetView.swift
Labels: 디자인, 수정, 🥑 창준, 👻 민재, :tiger: 인선, 🦎 대홍

#23 [Add] Custom Navigation ToolBar 추가 #3
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomNavigation.swift
  FinalHrmiProjects/Resource/View +.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선

#27 [Add]로그인 필요 다이얼로그 Custom Alert Dialog #26
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomAlert.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선

#28 [Add] StarRating 작성 #6
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Assets.xcassets/star.filled.symbolset/Contents.json
  FinalHrmiProjects/Assets.xcassets/star.filled.symbolset/star.filled.svg
  FinalHrmiProjects/Assets.xcassets/star.half.filled.symbolset/Contents.json
  FinalHrmiProjects/Assets.xcassets/star.half.filled.symbolset/star.half.filled.svg
  FinalHrmiProjects/Resource/Components/StarRating.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, 🦎 대홍

#34 [Add] DrinkInfoView
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomBottomSheet.swift
  FinalHrmiProjects/Resource/Components/DrinkGridCell.swift
  FinalHrmiProjects/Resource/Components/DrinkInfoSegment.swift
  FinalHrmiProjects/Resource/Components/DrinkListCell.swift
  FinalHrmiProjects/Resource/Components/DrinkSelectHorizontalScrollBar.swift
  FinalHrmiProjects/Resource/Components/PagerView.swift
  FinalHrmiProjects/Resource/Components/StarRating.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoGrid.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoList.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoView.swift
  FinalHrmiProjects/View/DrinkInfo/EnabledBottomSheetView.swift
Labels: 디자인, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#40 [Add] 버튼 애니메이션 없는 버튼 구현 #39
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Button.swift
Labels: 디자인, 🥑 창준, 🫧 세희, :tiger: 인선, 🦎 대홍

#30 [Add] RootView 작성, square.grid.fill/squre.gird Symbol 추가, medium10 Fo…
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Assets.xcassets/square.grid.fill.symbolset/Contents.json
  FinalHrmiProjects/Assets.xcassets/square.grid.fill.symbolset/square.grid.filled.svg
  FinalHrmiProjects/Assets.xcassets/square.grid.symbolset/Contents.json
  FinalHrmiProjects/Assets.xcassets/square.grid.symbolset/square.grid.svg
  FinalHrmiProjects/ContentView.swift
  FinalHrmiProjects/Resource/Font +.swift
  FinalHrmiProjects/View/RootView/RootView.swift
  FinalHrmiProjects/View/RootView/TabItem.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, 🦎 대홍

#33 [Add] LoginView UI작업 + (다크 모드 + 라이트 모드) 대응 Theme파일 추가
  FinalHrmiProjects/Assets.xcassets/Google.imageset/Contents.json
  FinalHrmiProjects/Assets.xcassets/Google.imageset/Google.png
  FinalHrmiProjects/Assets.xcassets/Image.imageset/Contents.json
  FinalHrmiProjects/Assets.xcassets/Image.imageset/제목 4.png
  FinalHrmiProjects/Assets.xcassets/Kakao.imageset/Contents.json
  FinalHrmiProjects/Assets.xcassets/Kakao.imageset/Kakao.png
  FinalHrmiProjects/Assets.xcassets/applelogin.imageset/Contents.json
  FinalHrmiProjects/Assets.xcassets/applelogin.imageset/applelogin.png
  FinalHrmiProjects/Resource/Font +.swift
  FinalHrmiProjects/View/LogIn/LogInView.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선

#49 [Add] 10.MypageView UI 작업
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects.xcodeproj/project.xcworkspace/xcuserdata/hongsehui.xcuserdatad/UserInterfaceState.xcuserstate
  FinalHrmiProjects/View/Mypage/MypageDetail/AlarmStackView.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/SelectedProfilePhotoView.swift
  FinalHrmiProjects/View/Mypage/MypageView.swift
  FinalHrmiProjects/View/Mypage/SettingView.swift
Labels: 디자인, 🥑 창준, 👻 민재, :tiger: 인선, 🦎 대홍

#43 [Add] Tag 관련 Method 담고있는 namespace #41
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Handler.swift
Labels: 기능, 🥑 창준, 🫧 세희, :tiger: 인선, 🦎 대홍

#44 DrinkDetailView 디자인
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomNavigation.swift
  FinalHrmiProjects/Resource/Components/StarRating.swift
  FinalHrmiProjects/Resource/Font +.swift
  FinalHrmiProjects/Resource/Formatter.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/DrinkDetailView.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/PeferencesChart.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/PostListCell.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/TaggedTrendingPosts.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/TastingNotes.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/WellMatched.swift
Labels: 디자인, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#59 Re: [Add] DrinkDetailView
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomNavigation.swift
  FinalHrmiProjects/Resource/Components/StarRating.swift
  FinalHrmiProjects/Resource/Font +.swift
  FinalHrmiProjects/Resource/Formatter.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/DrinkDetailView.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/PeferencesChart.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/PostListCell.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/TaggedTrendingPosts.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/TastingNotes.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/WellMatched.swift
Labels: 디자인, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#46 [Add] PostView UI 구현 #19
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomTextSegment.swift
  FinalHrmiProjects/Resource/Components/PostCell.swift
  FinalHrmiProjects/View/Posts/PostGrid.swift
  FinalHrmiProjects/View/Posts/PostsView.swift
Labels: 디자인, 🥑 창준, 🫧 세희, :tiger: 인선, 🦎 대홍

#42 [Add] MainView
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Assets.xcassets/sun.imageset/Contents.json
  FinalHrmiProjects/Assets.xcassets/sun.imageset/sun.png
  FinalHrmiProjects/Resource/Font +.swift
  FinalHrmiProjects/View/Main/MainView.swift
  FinalHrmiProjects/View/Main/MainViewComponents/SuggestDrinkCell.swift
  FinalHrmiProjects/View/Main/MainViewComponents/SuggestDrinkView.swift
  FinalHrmiProjects/View/Main/MainViewComponents/TodaySulView.swift
  FinalHrmiProjects/View/Main/MainViewComponents/WeatherView.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선

#51 AddTagView UI 구현 #31
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Assets.xcassets/Image.imageset/Contents.json
  FinalHrmiProjects/Assets.xcassets/canuca.imageset/Contents.json
  FinalHrmiProjects/Assets.xcassets/canuca.imageset/제목 5.png
  FinalHrmiProjects/Resource/Button.swift
  FinalHrmiProjects/Resource/Components/DrinkGridCell.swift
  FinalHrmiProjects/Resource/Components/DrinkListCell.swift
  FinalHrmiProjects/Resource/Components/StarRating.swift
  FinalHrmiProjects/View/Record/AddTagView.swift
  FinalHrmiProjects/View/Record/DrinkTagScroll.swift
  FinalHrmiProjects/View/Record/PhotoPicker.swift
  FinalHrmiProjects/View/Record/PhotoSelectPagingTab.swift
  FinalHrmiProjects/View/Record/RecordView.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, 🦎 대홍

#54 SearchTagView UI 구현 #53
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/View/Record/SearchTagView.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, 🦎 대홍

#71 Re: LikedView & DrinkInfoView & PagerView 리팩토링 + CustomScrollView 작성
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomScrollView.swift
  FinalHrmiProjects/Resource/Components/CustomTextSegment.swift
  FinalHrmiProjects/Resource/Components/DrinkInfoSegment.swift
  FinalHrmiProjects/Resource/Components/DrinkSelectHorizontalScrollBar.swift
  FinalHrmiProjects/Resource/Components/PagerView.swift
  FinalHrmiProjects/Resource/Components/PostCell.swift
  FinalHrmiProjects/Resource/Components/StarRating.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/DrinkDetailView.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoGrid.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoList.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoView.swift
  FinalHrmiProjects/View/Liked/LikedDrinkList.swift
  FinalHrmiProjects/View/Liked/LikedPostGrid.swift
  FinalHrmiProjects/View/Liked/LikedView.swift
  FinalHrmiProjects/View/Posts/PostDetailView.swift
Labels: 디자인, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#72 [Add]: MainView Design #36.
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Assets.xcassets/sun.imageset/Contents.json
  FinalHrmiProjects/Assets.xcassets/sun.imageset/sun.png
  FinalHrmiProjects/View/Main/MainView.swift
  FinalHrmiProjects/View/Main/SuggestDrinkCell.swift
  FinalHrmiProjects/View/Main/SuggestDrinkView.swift
  FinalHrmiProjects/View/Main/TodayDrinkRecommendedView.swift
  FinalHrmiProjects/View/Main/WeatherView.swift
Labels: 디자인, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#57 [Add] CustomSettingDialog + CustomStarDialog Add #48
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomDialog.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선

#66 Feature/change user name view/design
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/View +.swift
  FinalHrmiProjects/View/Mypage/ChangeUserNameView.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선

#73 [Add] MypageView 추가 및 네비게이션 #25
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects.xcodeproj/project.xcworkspace/xcuserdata/hongsehui.xcuserdatad/UserInterfaceState.xcuserstate
  FinalHrmiProjects/View/Mypage/MypageDetail/AlarmStoreListCell.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/AlarmStoreView.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/ChangeUserNameView.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/ProfilePhotoPicker.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/SettingPhotoPicker.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/UserProfileView.swift
  FinalHrmiProjects/View/Mypage/MypageView.swift
  FinalHrmiProjects/View/Mypage/SettingView.swift
Labels: 버그, 디자인, 수정, 🥑 창준, 👻 민재, :tiger: 인선, 🦎 대홍

#74 [Add] SettingView 추가 및 코드 정리 #50
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects.xcodeproj/project.xcworkspace/xcuserdata/hongsehui.xcuserdatad/UserInterfaceState.xcuserstate
  FinalHrmiProjects/View/Mypage/SettingDetail/AppServiceInfoView.swift
  FinalHrmiProjects/View/Mypage/SettingDetail/NoticeView.swift
  FinalHrmiProjects/View/Mypage/SettingView.swift
Labels: 버그, 디자인, 수정, 🥑 창준, 👻 민재, :tiger: 인선, 🦎 대홍
