Repository JUDA-Hrmi/JUDA, pull requests merged in 2024-02, with the labels that each got.

#75 [Add & Edit] PostDetailView 수정 및 세부 뷰 파일 나누기 / PostReportView(게시글 신고뷰) UI 구현 및 세부 뷰 파일 나누기
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Assets.xcassets/canuca.imageset/canuca.png
  FinalHrmiProjects/ContentView.swift
  FinalHrmiProjects/Resource/Components/PostCell.swift
  FinalHrmiProjects/Resource/Components/SearchBar.swift
  FinalHrmiProjects/Resource/View +.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/DrinkDetailView.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoView.swift
  FinalHrmiProjects/View/Main/MainView.swift
  FinalHrmiProjects/View/Posts/NavigationPostsView.swift
  FinalHrmiProjects/View/Posts/PostDetailView.swift
  FinalHrmiProjects/View/Posts/PostDrinkRating.swift
  FinalHrmiProjects/View/Posts/PostGrid.swift
  FinalHrmiProjects/View/Posts/PostInfo.swift
  FinalHrmiProjects/View/Posts/PostPhotoScroll.swift
  FinalHrmiProjects/View/Posts/PostReportButton.swift
  FinalHrmiProjects/View/Posts/PostReportContent.swift
  FinalHrmiProjects/View/Posts/PostReportTitle.swift
  FinalHrmiProjects/View/Posts/PostReportToolbar.swift
  FinalHrmiProjects/View/Posts/PostReportView.swift
  FinalHrmiProjects/View/Posts/PostTags.swift
  FinalHrmiProjects/View/Posts/PostsView.swift
  FinalHrmiProjects/View/Record/SearchTagView.swift
  FinalHrmiProjects/View/RootView/RootView.swift
Labels: 버그, 디자인, 기능, 수정, 🥑 창준, 🫧 세희, :tiger: 인선, 🦎 대홍

#60 WritingView UI 구현 #45
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/View/Record/FoodTagAddTextField.swift
  FinalHrmiProjects/View/Record/FoodTagVertical.swift
  FinalHrmiProjects/View/Record/FoodTagXmarkButton.swift
  FinalHrmiProjects/View/Record/SelectedPhotoHorizontalScroll.swift
  FinalHrmiProjects/View/Record/WritingView.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, 🦎 대홍

#77 [Add] CustomRatingDialog 추가 #76
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/ContentView.swift
  FinalHrmiProjects/Resource/Button.swift
  FinalHrmiProjects/Resource/Components/CustomRatingDialog.swift
  FinalHrmiProjects/View/Record/AddTagView.swift
  FinalHrmiProjects/View/Record/DrinkTagScroll.swift
  FinalHrmiProjects/View/Record/SearchTagView.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, 🦎 대홍

#82 [Edit]: WritingView -> RecordView + 뷰간 연결 #81
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/View/Posts/PostDetailView.swift
  FinalHrmiProjects/View/Record/AddTagView.swift
  FinalHrmiProjects/View/Record/FoodTagAddTextField.swift
  FinalHrmiProjects/View/Record/RecordView.swift
  FinalHrmiProjects/View/Record/SelectedPhotoHorizontalScroll.swift
  FinalHrmiProjects/View/Record/WritingView.swift
Labels: 디자인, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#91 Feature/userprofile/logic
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/View/Mypage/MypageDetail/UserProfileView.swift
  FinalHrmiProjects/View/Mypage/MypageView.swift
  FinalHrmiProjects/View/Mypage/NavigationProfileView.swift
  FinalHrmiProjects/View/Posts/PostInfo.swift
  FinalHrmiProjects/View/Posts/PostsView.swift
  FinalHrmiProjects/View/RootView/RootView.swift
Labels: 디자인, 기능, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선

#88 [Edit] Refactoring - PagerView 에서 TabView 로 수정 & 일부 수정
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/DrinkSelectHorizontalScrollBar.swift
  FinalHrmiProjects/Resource/Components/PagerView.swift
  FinalHrmiProjects/Resource/Components/SearchBar.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoView.swift
  FinalHrmiProjects/View/Liked/LikedView.swift
  FinalHrmiProjects/View/Mypage/MypageView.swift
  FinalHrmiProjects/View/Posts/PostsView.swift
  FinalHrmiProjects/View/Record/SearchTagView.swift
Labels: 디자인, 수정, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#90 [Edit] CustomScrollView 에서 ScrollView + ViewThatFits 로 수정 #89
  FinalHrmiProjects/Resource/Components/CustomScrollView.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoGrid.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoList.swift
  FinalHrmiProjects/View/Liked/LikedDrinkList.swift
  FinalHrmiProjects/View/Liked/LikedPostGrid.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/AlarmStoreView.swift
  FinalHrmiProjects/View/Mypage/MypageView.swift
  FinalHrmiProjects/View/Posts/PostGrid.swift
  FinalHrmiProjects/View/Record/SearchTagView.swift
Labels: 디자인, 수정, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#93 [Edit] NavigationPostsView 수정 #92
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  FinalHrmiProjects/View/Posts/NavigationPostsView.swift
  FinalHrmiProjects/View/Posts/PostTags.swift
Labels: 디자인, 수정, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#95 [Edit] TabView 내부에 각각 NavigationStack 사용하도록 수정
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/FinalHrmiProjectsApp.swift
  FinalHrmiProjects/View/ContentView/ContentView.swift
  FinalHrmiProjects/View/ContentView/TabItem.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoGrid.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoList.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoView.swift
  FinalHrmiProjects/View/Liked/LikedDrinkList.swift
  FinalHrmiProjects/View/Liked/LikedPostGrid.swift
  FinalHrmiProjects/View/Liked/LikedView.swift
  FinalHrmiProjects/View/LogIn/LogInView.swift
  FinalHrmiProjects/View/Main/MainView.swift
  FinalHrmiProjects/View/Main/SuggestDrinkView.swift
  FinalHrmiProjects/View/Main/TodayDrinkRecommendedView.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/UserProfileView.swift
  FinalHrmiProjects/View/Mypage/MypageView.swift
  FinalHrmiProjects/View/Mypage/NavigationProfileView.swift
  FinalHrmiProjects/View/Posts/PostDrinkRating.swift
  FinalHrmiProjects/View/Posts/PostGrid.swift
  FinalHrmiProjects/View/Posts/PostInfo.swift
  FinalHrmiProjects/View/Posts/PostsView.swift
  FinalHrmiProjects/ViewModel/AppViewModel.swift
Labels: 디자인, 수정, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#99 [Edit] UIKit PHPicker -> SwiftUI PhotosPicker #98
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Resource/Components/CustomDialog.swift
  FinalHrmiProjects/Resource/Components/CustomRatingDialog.swift
  FinalHrmiProjects/Resource/Components/CustomScrollView.swift
  FinalHrmiProjects/Resource/Components/LibraryPhotosPicker.swift
  FinalHrmiProjects/Resource/Errors.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/AlarmStoreView.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/ProfilePhotoPicker.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/SettingPhotoPicker.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/UserProfileView.swift
  FinalHrmiProjects/View/Mypage/SettingView.swift
  FinalHrmiProjects/View/Posts/PostDetailView.swift
  FinalHrmiProjects/View/Record/AddTagView.swift
  FinalHrmiProjects/View/Record/PhotoPicker.swift
  FinalHrmiProjects/View/Record/PhotoSelectPagingTab.swift
  FinalHrmiProjects/View/Record/SearchTagView.swift
Labels: 디자인, 수정, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#100 Refactoring/design
  FinalHrmiProjects.xcodeproj/project.pbxproj
  FinalHrmiProjects/Assets.xcassets/AppIcon.appiconset/Contents.json
  FinalHrmiProjects/Assets.xcassets/AppIcon.appiconset/hrmi.png
  FinalHrmiProjects/FinalHrmiProjectsApp.swift
  FinalHrmiProjects/Resource/Components/CustomAlert.swift
  FinalHrmiProjects/Resource/Components/CustomBottomSheet.swift
  FinalHrmiProjects/Resource/Components/CustomTextSegment.swift
  FinalHrmiProjects/Resource/Components/DrinkGridCell.swift
  FinalHrmiProjects/Resource/Components/DrinkInfoSegment.swift
  FinalHrmiProjects/Resource/Components/DrinkListCell.swift
  FinalHrmiProjects/Resource/Components/PostCell.swift
  FinalHrmiProjects/Resource/Components/SearchBar.swift
  FinalHrmiProjects/Resource/Font +.swift
  FinalHrmiProjects/Resource/Formatter.swift
  FinalHrmiProjects/Resource/UIApplication +.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/DrinkDetailView.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/PeferenceChart.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/TaggedTrendingPosts.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/TastingNotes.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkDetail/WellMatched.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoGrid.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoList.swift
  FinalHrmiProjects/View/DrinkInfo/DrinkInfoView.swift
  FinalHrmiProjects/View/Liked/LikedDrinkList.swift
  FinalHrmiProjects/View/Main/MainView.swift
  FinalHrmiProjects/View/Main/PostOrLogin.swift
  FinalHrmiProjects/View/Main/SuggestDrink.swift
  FinalHrmiProjects/View/Main/TodayDrinkRecommended.swift
  FinalHrmiProjects/View/Main/WeatherAndFood.swift
  FinalHrmiProjects/View/Main/WeatherView.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/AlarmStoreListCell.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/ChangeUserNameView.swift
  FinalHrmiProjects/View/Mypage/MypageDetail/UserProfileView.swift
  FinalHrmiProjects/View/Mypage/MypageView.swift
  FinalHrmiProjects/View/Mypage/NavigationProfileView.swift
  FinalHrmiProjects/View/Mypage/SettingDetail/AppServiceInfoView.swift
  FinalHrmiProjects/View/Mypage/SettingDetail/NoticeView.swift
  FinalHrmiProjects/View/Posts/PostDetailView.swift
  FinalHrmiProjects/View/Posts/PostDrinkRating.swift
  FinalHrmiProjects/View/Posts/PostGrid.swift
  FinalHrmiProjects/View/Posts/PostInfo.swift
  FinalHrmiProjects/View/Posts/PostPhotoScroll.swift
  FinalHrmiProjects/View/Posts/PostReportButton.swift
  FinalHrmiProjects/View/Posts/PostReportContent.swift
  FinalHrmiProjects/View/Posts/PostReportToolbar.swift
  FinalHrmiProjects/View/Posts/PostReportView.swift
  FinalHrmiProjects/View/Posts/PostTags.swift
  FinalHrmiProjects/View/Posts/PostsView.swift
  FinalHrmiProjects/View/Record/AddTagView.swift
  FinalHrmiProjects/View/Record/DrinkTagScroll.swift
  FinalHrmiProjects/View/Record/FoodTagAddTextField.swift
  FinalHrmiProjects/View/Record/FoodTagVertical.swift
  FinalHrmiProjects/View/Record/FoodTagXmarkButton.swift
  FinalHrmiProjects/View/Record/PhotoSelectPagingTab.swift
  FinalHrmiProjects/View/Record/RecordView.swift
  FinalHrmiProjects/View/Record/SearchTagView.swift
  FinalHrmiProjects/View/Record/SelectedPhotoHorizontalScroll.swift
Labels: 디자인, 수정, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#110 Feature/main view/login logic
  JUDA.xcodeproj/project.pbxproj
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/Main/AiViewModel.swift
  JUDA/View/Main/TodayDrinkRecommended.swift
  JUDA/View/Main/WeatherAndFood.swift
Labels: API, 수정

#105 Feature/apple sign in
  .gitignore
  JUDA.xcodeproj/project.pbxproj
  JUDA/Assets.xcassets/applelogin.imageset/applelogin.png
  JUDA/Assets.xcassets/defaultprofileimage.imageset/Contents.json
  JUDA/Assets.xcassets/defaultprofileimage.imageset/defaultprofileimage.png
  JUDA/JUDA.entitlements
  JUDA/JUDAApp.swift
  JUDA/Model/User.swift
  JUDA/Resource/Components/CustomLoadingView.swift
  JUDA/Resource/Formatter.swift
  JUDA/Resource/Lottie/Clouds.json
  JUDA/Resource/Lottie/Loading.json
  JUDA/Resource/Lottie/Rain.json
  JUDA/Resource/Lottie/Snow.json
  JUDA/Resource/Lottie/Sun.json
  JUDA/Resource/Lottie/Thunder.json
  JUDA/Resource/View +.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/LogIn/LogInView.swift
  JUDA/View/LogIn/ProfileSettingView.swift
  JUDA/View/LogIn/TermsAndVerificationView.swift
  JUDA/View/LogIn/UserAgreementView.swift
  JUDA/View/Main/MainView.swift
  JUDA/View/Main/PostOrLogin.swift
  JUDA/View/Main/SuggestDrink.swift
  JUDA/View/Main/TodayDrinkRecommended.swift
  JUDA/View/Main/WeatherAndFood.swift
  JUDA/View/Mypage/MypageDetail/AlarmStoreView.swift
  JUDA/View/Mypage/MypageDetail/ChangeUserNameView.swift
  JUDA/View/Mypage/MypageDetail/UserProfileView.swift
  JUDA/View/Mypage/MypageView.swift
  JUDA/View/Mypage/NavigationProfileView.swift
  JUDA/View/Mypage/SettingDetail/AppServiceInfoView.swift
  JUDA/View/Mypage/SettingDetail/NoticeView.swift
  JUDA/View/Mypage/SettingView.swift
  JUDA/View/Posts/NavigationPostsView.swift
  JUDA/View/Splash/SplashView.swift
  JUDA/View/Trash/IdentityVerificationView.swift
  JUDA/ViewModel/App/AppViewModel.swift
  JUDA/ViewModel/Auth/AuthService.swift
Labels: 기능, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#112 [Add] CustomLoadingView - 로그인, 가입, 탈퇴 시 딜레이에 적용
  JUDA.xcodeproj/project.pbxproj
  JUDA/JUDAApp.swift
  JUDA/Resource/Components/CustomLoadingView.swift
  JUDA/Resource/View +.swift
  JUDA/View/LogIn/LogInView.swift
  JUDA/View/LogIn/ProfileSettingView.swift
  JUDA/View/Mypage/SettingView.swift
  JUDA/ViewModel/Auth/AuthService.swift
Labels: 디자인, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#113 술 테스트 데이터 파이어베이스 업로드 코드 작성 #106
  JUDA.xcodeproj/project.pbxproj
  JUDA/Model/Drink.swift
  JUDA/ViewModel/App/DrinkUploadViewModel.swift
Labels: 데이터, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#116 Feature/mypage firebase connect/say
  JUDA.xcodeproj/project.pbxproj
  JUDA/JUDAApp.swift
  JUDA/Model/User.swift
  JUDA/Resource/Components/DrinkInfoSegment.swift
  JUDA/Resource/Theme.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA/View/LogIn/LogInView.swift
  JUDA/View/Main/MainView.swift
  JUDA/View/Mypage/MypageDetail/AlarmStoreListCell.swift
  JUDA/View/Mypage/MypageDetail/AlarmStoreView.swift
  JUDA/View/Mypage/MypageDetail/ChangeUserNameView.swift
  JUDA/View/Mypage/MypageDetail/UserProfileView.swift
  JUDA/View/Mypage/MypageView.swift
  JUDA/View/Mypage/NavigationProfileView.swift
  JUDA/View/Mypage/SettingView.swift
  JUDA/View/Mypage/unauthenticatedMypageView.swift
  JUDA/View/Splash/SplashView.swift
  JUDA/ViewModel/App/AppViewModel.swift
  JUDA/ViewModel/Auth/AuthService.swift
  JUDA/ViewModel/Mypage/MypageViewModel.swift
Labels: 기능, 데이터, API, 수정, 🫧 세희

#117 [Add & Edit] RecordViewModel Firebase 관련 로직 작성 및 User, Drink 데이터 모델, UI 수정
  JUDA.xcodeproj/project.pbxproj
  JUDA/Model/Drink.swift
  JUDA/Model/Post.swift
  JUDA/Model/User.swift
  JUDA/Resource/Components/DrinkListCell.swift
  JUDA/Resource/Components/SearchBar.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/DrinkInfo/DrinkInfoList.swift
  JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA/View/Liked/LikedDrinkList.swift
  JUDA/View/LogIn/ProfileSettingView.swift
  JUDA/View/Posts/PostsView.swift
  JUDA/View/Record/AddTagView.swift
  JUDA/View/Record/DrinkTagScroll.swift
  JUDA/View/Record/FoodTagAddTextField.swift
  JUDA/View/Record/FoodTagVertical.swift
  JUDA/View/Record/FoodTagXmarkButton.swift
  JUDA/View/Record/PhotoSelectPagingTab.swift
  JUDA/View/Record/RecordView.swift
  JUDA/View/Record/SearchTagView.swift
  JUDA/View/Record/SelectedPhotoHorizontalScroll.swift
  JUDA/ViewModel/App/DrinkUploadViewModel.swift
  JUDA/ViewModel/Auth/AuthService.swift
  JUDA/ViewModel/Record/RecordViewModel.swift
Labels: 데이터, 🥑 창준, 👻 민재, 🫧 세희, 🦎 대홍

#123 [Edit] PostView & PostDetaiview & RecordView 관련 ViewModel 로직 구현 및 수정 …
  JUDA.xcodeproj/project.pbxproj
  JUDA/Model/Drink.swift
  JUDA/Model/Post.swift
  JUDA/Model/User.swift
  JUDA/Resource/Components/PostCell.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/DrinkInfo/DrinkDetail/TaggedTrendingPosts.swift
  JUDA/View/Liked/LikedPostGrid.swift
  JUDA/View/Mypage/MypageDetail/AlarmStoreView.swift
  JUDA/View/Mypage/MypageView.swift
  JUDA/View/Mypage/NavigationProfileView.swift
  JUDA/View/Posts/NavigationPostsView.swift
  JUDA/View/Posts/PostDetailView.swift
  JUDA/View/Posts/PostDrinkRating.swift
  JUDA/View/Posts/PostGrid.swift
  JUDA/View/Posts/PostInfo.swift
  JUDA/View/Posts/PostPhotoScroll.swift
  JUDA/View/Posts/PostTags.swift
  JUDA/View/Posts/PostsView.swift
  JUDA/View/Record/AddTagView.swift
  JUDA/View/Record/DrinkTagScroll.swift
  JUDA/View/Record/RecordView.swift
  JUDA/View/Record/SearchTagView.swift
  JUDA/ViewModel/Auth/AuthService.swift
  JUDA/ViewModel/Posts/PostsViewModel.swift
  JUDA/ViewModel/Record/RecordViewModel.swift
Labels: 기능, 데이터, 수정, 🥑 창준, 🫧 세희, :tiger: 인선, 🦎 대홍

#122 Feature/drink firebase
  JUDA.xcodeproj/project.pbxproj
  JUDA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  JUDA/Info.plist
  JUDA/Model/Drink.swift
  JUDA/Model/DrinkDummyData.swift
  JUDA/Model/DummyModel.swift
  JUDA/Resource/Components/CircularLoaderView.swift
  JUDA/Resource/Components/CustomBottomSheet.swift
  JUDA/Resource/Components/CustomTextSegment.swift
  JUDA/Resource/Components/DrinkGridCell.swift
  JUDA/Resource/Components/DrinkInfoSegment.swift
  JUDA/Resource/Components/DrinkListCell.swift
  JUDA/Resource/Components/PostCell.swift
  JUDA/Resource/Components/SearchBar.swift
  JUDA/Resource/Components/ShimmerDrinkGridCell.swift
  JUDA/Resource/Components/ShimmerDrinkListCell.swift
  JUDA/Resource/Components/ShimmerPostCell.swift
  JUDA/Resource/Debouncer.swift
  JUDA/Resource/Font +.swift
  JUDA/Resource/Formatter.swift
  JUDA/Resource/URL +.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/DrinkInfo/DrinkDetail/DrinkDetailView.swift
  JUDA/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  JUDA/View/DrinkInfo/DrinkDetail/KoreanTastingNotes.swift
  JUDA/View/DrinkInfo/DrinkDetail/PeferenceChart.swift
  JUDA/View/DrinkInfo/DrinkDetail/TastingNotes.swift
  JUDA/View/DrinkInfo/DrinkDetail/WellMatched.swift
  JUDA/View/DrinkInfo/DrinkInfoGrid.swift
  JUDA/View/DrinkInfo/DrinkInfoList.swift
  JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA/View/Liked/LikedDrinkList.swift
  JUDA/View/Liked/LikedView.swift
  JUDA/View/LogIn/LogInView.swift
  JUDA/View/Main/MainView.swift
  JUDA/View/Main/TodayDrinkRecommended.swift
  JUDA/View/Main/WeatherAndFood.swift
  JUDA/View/Posts/NavigationPostsView.swift
  JUDA/View/Posts/PostDrinkRating.swift
  JUDA/View/Posts/PostTags.swift
  JUDA/View/Posts/PostsView.swift
  JUDA/View/Record/AddTagView.swift
  JUDA/View/Record/SearchTagView.swift
  JUDA/ViewModel/Auth/AuthService.swift
  JUDA/ViewModel/Drink/DrinkViewModel.swift
  JUDA/ViewModel/Drink/SearchDrinkViewModel.swift
  JUDA/ViewModel/DrinkInfo/DrinkInfoViewModel.swift
  JUDA/ViewModel/JsonUploadFiles/DrinkUploadViewModel.swift
  JUDA/ViewModel/Liked/LikedViewModel.swift
  JUDA/ViewModel/Posts/PostsViewModel.swift
  JUDA/ViewModel/Record/RecordViewModel.swift
Labels: 디자인, 기능, 데이터, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#125 MainView 오늘의 추천 술 삭제 및 Top3 View 생성
  JUDA.xcodeproj/project.pbxproj
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/Main/AiViewModel.swift
  JUDA/View/Main/DrinkTopView.swift
  JUDA/View/Main/MainView.swift
  JUDA/View/Main/PostOrLogin.swift
  JUDA/View/Main/PostTopView.swift
  JUDA/View/Main/SuggestDrink.swift
  JUDA/View/Main/WeatherAndFood.swift
  JUDA/View/Main/WeatherViewModel.swift
Labels: 디자인, 기능, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선

#126 DrinkDetail (Post, Drink) & Main (Post, Drink) - Firebase 연결
  JUDA.xcodeproj/project.pbxproj
  JUDA/JUDAApp.swift
  JUDA/Model/Post.swift
  JUDA/Model/User.swift
  JUDA/Resource/Components/DrinkListCell.swift
  JUDA/Resource/Components/PostCell.swift
  JUDA/Resource/Components/PostListCell.swift
  JUDA/Resource/Components/ShimmerPostListCell.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/DrinkInfo/DrinkDetail/DrinkDetailView.swift
  JUDA/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  JUDA/View/DrinkInfo/DrinkDetail/KoreanTastingNotes.swift
  JUDA/View/DrinkInfo/DrinkDetail/TaggedTrendingPosts.swift
  JUDA/View/DrinkInfo/DrinkDetail/WellMatched.swift
  JUDA/View/DrinkInfo/DrinkInfoList.swift
  JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA/View/Liked/LikedDrinkList.swift
  JUDA/View/Liked/LikedPostGrid.swift
  JUDA/View/Liked/LikedView.swift
  JUDA/View/LogIn/LogInView.swift
  JUDA/View/Main/DrinkTopView.swift
  JUDA/View/Main/MainView.swift
  JUDA/View/Main/PostTopView.swift
  JUDA/View/Main/WeatherAndFood.swift
  JUDA/View/Mypage/MypageView.swift
  JUDA/View/Mypage/SettingView.swift
  JUDA/View/Posts/NavigationPostsView.swift
  JUDA/View/Posts/PostDetailView.swift
  JUDA/View/Posts/PostDrinkRating.swift
  JUDA/View/Posts/PostGrid.swift
  JUDA/View/Posts/PostPhotoScroll.swift
  JUDA/View/Posts/PostTags.swift
  JUDA/View/Record/RecordView.swift
  JUDA/View/Splash/SplashView.swift
  JUDA/ViewModel/Auth/AuthService.swift
  JUDA/ViewModel/Liked/LikedViewModel.swift
  JUDA/ViewModel/Main/MainViewModel.swift
  JUDA/ViewModel/Mypage/AlarmViewModell.swift
  JUDA/ViewModel/Mypage/MyPageViewModel.swift
  JUDA/ViewModel/Posts/PostsViewModel.swift
  JUDA/ViewModel/Record/RecordViewModel.swift
Labels: 디자인, 기능, API, 수정, 👻 민재, 🫧 세희, :tiger: 인선, 🦎 대홍

#129 [edit & Add & feat] 포스트 업로드 로직 수정 및 포스트 검색 기능 구현 #119
  JUDA.xcodeproj/project.pbxproj
  JUDA/Model/Post.swift
  JUDA/Model/Report.swift
  JUDA/Resource/Components/PostCell.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  JUDA/View/DrinkInfo/DrinkDetail/TaggedTrendingPosts.swift
  JUDA/View/Liked/LikedPostGrid.swift
  JUDA/View/Main/PostTopView.swift
  JUDA/View/Mypage/MypageView.swift
  JUDA/View/Posts/NavigationPostsView.swift
  JUDA/View/Posts/PostDetail/PostDetailView.swift
  JUDA/View/Posts/PostDetail/PostDrinkRating.swift
  JUDA/View/Posts/PostDetail/PostInfo.swift
  JUDA/View/Posts/PostDetail/PostPhotoScroll.swift
  JUDA/View/Posts/PostDetail/PostTags.swift
  JUDA/View/Posts/PostGrid.swift
  JUDA/View/Posts/PostPhotoScroll.swift
  JUDA/View/Posts/PostReport/PostReportButton.swift
  JUDA/View/Posts/PostReport/PostReportContent.swift
  JUDA/View/Posts/PostReport/PostReportTitle.swift
  JUDA/View/Posts/PostReport/PostReportToolbar.swift
  JUDA/View/Posts/PostReport/PostReportView.swift
  JUDA/View/Posts/PostSearchList.swift
  JUDA/View/Posts/PostSearchListCell.swift
  JUDA/View/Posts/PostsView.swift
  JUDA/View/Record/RecordView.swift
  JUDA/ViewModel/Posts/PostsViewModel.swift
  JUDA/ViewModel/Posts/SearchPostsViewModel.swift
  JUDA/ViewModel/Record/RecordViewModel.swift
Labels: 기능, 데이터, 수정

#131 [Edit & Feat] 검색 기능 버그 수정, 태그 탭 후 태그 관련 포스트들 필터링 후 보여주기 완. #119
  JUDA.xcodeproj/project.pbxproj
  JUDA/Resource/Components/PostCell.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/DrinkInfo/DrinkDetail/TaggedTrendingPosts.swift
  JUDA/View/Liked/LikedPostGrid.swift
  JUDA/View/Main/PostTopView.swift
  JUDA/View/Posts/NavigationPostsView.swift
  JUDA/View/Posts/PostDetail/PostDetailView.swift
  JUDA/View/Posts/PostDetail/PostInfo.swift
  JUDA/View/Posts/PostDetail/PostTags.swift
  JUDA/View/Posts/PostGrid.swift
  JUDA/View/Posts/PostsView.swift
  JUDA/View/Record/RecordView.swift
  JUDA/ViewModel/Posts/PostsViewModel.swift
  JUDA/ViewModel/Posts/SearchPostsViewModel.swift
Labels: 버그, 디자인, 기능, 데이터, 수정

#130 [Add] navigationProfileView 작성 & profileImage 수정
  JUDA.xcodeproj/project.pbxproj
  JUDA/Resource/Components/PostCell.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/Main/PostTopView.swift
  JUDA/View/Mypage/MypageDetail/AlarmStoreListCell.swift
  JUDA/View/Mypage/MypageDetail/ChangeUserNameView.swift
  JUDA/View/Mypage/MypageDetail/UserProfileView.swift
  JUDA/View/Mypage/MypageView.swift
  JUDA/View/Mypage/NavigationProfileView.swift
  JUDA/View/Mypage/unauthenticatedMypageView.swift
  JUDA/View/Posts/PostDetail/PostDetailView.swift
  JUDA/View/Posts/PostDetail/PostInfo.swift
  JUDA/View/Posts/PostGrid.swift
  JUDA/ViewModel/Auth/AuthService.swift
  JUDA/ViewModel/Liked/LikedViewModel.swift
  JUDA/ViewModel/LogIn/LogInViewModel.swift
  JUDA/ViewModel/Main/MainViewModel.swift
  JUDA/ViewModel/Mypage/MyPageViewModel.swift
  JUDA/ViewModel/Posts/PostsViewModel.swift
  JUDA/ViewModel/Posts/SearchPostsViewModel.swift
Labels: 디자인, 기능, 데이터, 수정

#132 Feature/prompt/fix
  JUDA.xcodeproj/project.pbxproj
  JUDA/JUDAApp.swift
  JUDA/Resource/Bundle +.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/DrinkInfo/DrinkDetail/WellMatched.swift
  JUDA/View/Main/AiViewModel.swift
  JUDA/View/Main/WeatherAndFood.swift
  JUDA/View/Main/WeatherViewModel.swift
  JUDA/View/Splash/SplashView.swift
  JUDA/ViewModel/App/AppViewModel.swift
  JUDA/ViewModel/App/LocationManager.swift
  JUDA/ViewModel/Drink/AiWellMatchViewModel.swift
  JUDA/ViewModel/Main/AiViewModel.swift
  JUDA/ViewModel/Main/WeatherViewModel.swift
Labels: API, 🥑 창준, 👻 민재, 🫧 세희, :tiger: 인선

#136 [Edit & Feat & Bug] 네비게이션스택 처리 및 네비게이션 패스처리 그리고 자잘하지 않은 버그 수정 및 로직 추가…
  JUDA.xcodeproj/project.pbxproj
  JUDA/Resource/Components/DrinkGridCell.swift
  JUDA/Resource/Components/DrinkListCell.swift
  JUDA/Resource/Components/PostCell.swift
  JUDA/View/ContentView/ContentView.swift
  JUDA/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  JUDA/View/DrinkInfo/DrinkInfoGrid.swift
  JUDA/View/DrinkInfo/DrinkInfoList.swift
  JUDA/View/Liked/LikedDrinkList.swift
  JUDA/View/Main/DrinkTopView.swift
  JUDA/View/Main/MainView.swift
  JUDA/View/Main/PostTopView.swift
  JUDA/View/Mypage/AuthenticatedMypageView.swift
  JUDA/View/Mypage/MyPageView.swift
  JUDA/View/Mypage/MypageDetail/AlarmStoreView.swift
  JUDA/View/Mypage/MypageDetail/ChangeUserNameView.swift
  JUDA/View/Mypage/SettingView.swift
  JUDA/View/Mypage/UnauthenticatedMypageView.swift
  JUDA/View/Posts/PostDetail/PostDetailView.swift
  JUDA/View/Posts/PostDetail/PostInfo.swift
  JUDA/View/Record/RecordView.swift
  JUDA/View/Record/SearchTagView.swift
  JUDA/ViewModel/Auth/AuthService.swift
  JUDA/ViewModel/Mypage/MyPageViewModel.swift
  JUDA/ViewModel/Record/RecordViewModel.swift
Labels: 버그, 디자인, 기능, 데이터, 수정

#137 [Edit]: MainView Prompt HotFix
  JUDA.xcodeproj/project.pbxproj
  JUDA/View/Splash/SplashView.swift
  JUDA/ViewModel/Main/AiViewModel.swift
Labels: 긴급
