Repository JUDA-Hrmi/JUDA, pull requests merged in 2024-03, with the labels that each got.

#143 [Edit] FireStorageViewModel 생성 #142
  JUDA.xcodeproj/project.pbxproj
  JUDA/ViewModel/App/FireStorageViewModel.swift
Labels: 수정, 🥑 창준, 👻 민재

#148 [Edit] FirestorePostViewModel & FirestoreDrinkViewModel 뷰모델 리팩토링중 #142
  JUDA/Model/Drink.swift
  JUDA/ViewModel/Posts/FirestoreDrinkViewModel.swift
  JUDA/ViewModel/Posts/FirestorePostViewModel.swift
Labels: 수정

#155 [Edit] ViewModel 변경에 따른 LikedView 및 관련 View 코드 수정 #152
  JUDA/View/DrinkInfo/DrinkDetail/TaggedTrendingPosts.swift
  JUDA/View/Liked/LikedDrinkList.swift
  JUDA/View/Liked/LikedPostGrid.swift
  JUDA/View/Liked/LikedView.swift
  JUDA/View/Main/PostTopView.swift
  JUDA/View/Posts/PostGrid.swift
Labels: 수정, 🥑 창준, 👻 민재

#156 [Edit] MyPage 관련 View 코드 수정 #152
  JUDA/Model/User.swift
  JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA/View/Liked/LikedView.swift
  JUDA/View/Main/MainView.swift
  JUDA/View/Mypage/AuthenticatedMypageView.swift
  JUDA/View/Mypage/MyPageView.swift
  JUDA/View/Mypage/MypageDetail/AlarmStoreListCell.swift
  JUDA/View/Mypage/MypageDetail/AlarmStoreView.swift
  JUDA/View/Mypage/MypageDetail/ChangeUserNameView.swift
  JUDA/View/Mypage/MypageDetail/UserProfileView.swift
  JUDA/View/Mypage/NavigationProfileView.swift
  JUDA/View/Mypage/UnauthenticatedMypageView.swift
  JUDA/View/Posts/PostDetail/PostInfo.swift
  JUDA/View/Posts/PostsView.swift
  JUDA/ViewModel/App/NavigationRouter.swift
  JUDA/ViewModel/Drink/FirestoreDrinkService.swift
Labels: 수정, 🥑 창준, 👻 민재

#163 Refactoring/json upload #161
  JUDA_iOS/JUDA/ViewModel/JsonUploadFiles/DrinkUploadViewModel.swift
Labels: 데이터

#164 [Edit] enum DrinkJsonType case별로 맞지 않은 return 값을 갖고 있어 수정 #161
  JUDA_iOS/JUDA.xcodeproj/project.pbxproj
  JUDA_iOS/JUDA.xcodeproj/xcshareddata/xcschemes/JUDA.xcscheme
  JUDA_iOS/JUDA/ViewModel/Auth/AuthViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Drink/FirestoreDrinkService.swift
  JUDA_iOS/JUDA/ViewModel/JsonUploadFiles/DrinkUploadViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Main/MainViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Posts/FirestorePostService.swift
  JUDA_iOS/JUDA/ViewModel/Record/RecordViewModel.swift
Labels: 데이터

#167 Refactoring/view and view model
  JUDA_iOS/JUDA.xcodeproj/project.pbxproj
  JUDA_iOS/JUDA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  JUDA_iOS/JUDA.xcodeproj/xcshareddata/xcschemes/JUDA.xcscheme
  JUDA_iOS/JUDA/AppDelegate.swift
  JUDA_iOS/JUDA/JUDA.entitlements
  JUDA_iOS/JUDA/Model/Drink.swift
  JUDA_iOS/JUDA/Resource/Components/CustomBottomSheet.swift
  JUDA_iOS/JUDA/Resource/Components/DrinkListCell.swift
  JUDA_iOS/JUDA/Resource/Components/StarRating.swift
  JUDA_iOS/JUDA/Resource/Constants.swift
  JUDA_iOS/JUDA/Resource/Errors.swift
  JUDA_iOS/JUDA/Resource/Font +.swift
  JUDA_iOS/JUDA/View/ContentView/TabItem.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkDetail/DrinkDetails.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkDetail/TaggedTrendingPosts.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkInfoGrid.swift
  JUDA_iOS/JUDA/View/DrinkInfo/DrinkInfoView.swift
  JUDA_iOS/JUDA/View/Liked/LikedDrinkList.swift
  JUDA_iOS/JUDA/View/Liked/LikedPostGrid.swift
  JUDA_iOS/JUDA/View/Liked/LikedView.swift
  JUDA_iOS/JUDA/View/LogIn/ProfileSettingView.swift
  JUDA_iOS/JUDA/View/LogIn/TermsAndVerificationView.swift
  JUDA_iOS/JUDA/View/Main/MainView.swift
  JUDA_iOS/JUDA/View/Main/PostTopView.swift
  JUDA_iOS/JUDA/View/Mypage/AuthenticatedMypageView.swift
  JUDA_iOS/JUDA/View/Mypage/MyPageView.swift
  JUDA_iOS/JUDA/View/Mypage/MypageDetail/AlarmStoreListCell.swift
  JUDA_iOS/JUDA/View/Mypage/MypageDetail/AlarmStoreView.swift
  JUDA_iOS/JUDA/View/Mypage/MypageDetail/ChangeUserNameView.swift
  JUDA_iOS/JUDA/View/Mypage/MypageDetail/UserProfileView.swift
  JUDA_iOS/JUDA/View/Mypage/SettingView.swift
  JUDA_iOS/JUDA/View/Posts/PostDetail/PostDetailView.swift
  JUDA_iOS/JUDA/View/Posts/PostGrid.swift
  JUDA_iOS/JUDA/View/Record/RecordView.swift
  JUDA_iOS/JUDA/View/Splash/SplashView.swift
  JUDA_iOS/JUDA/View/Trash/IdentityVerificationView.swift
  JUDA_iOS/JUDA/ViewModel/App/FireStorageService.swift
  JUDA_iOS/JUDA/ViewModel/Auth/AuthViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Auth/FirebaseAuthService.swift
  JUDA_iOS/JUDA/ViewModel/Drink/DrinkViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Drink/FirestoreDrinkService.swift
  JUDA_iOS/JUDA/ViewModel/JsonUploadFiles/DrinkUploadViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Main/MainViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Posts/FirestorePostService.swift
  JUDA_iOS/JUDA/ViewModel/Posts/PostViewModel.swift
Labels: 수정

#168 [Edit] RecordView/PostsView 관련 코드 수정 #166
  JUDA_iOS/JUDA.xcodeproj/project.pbxproj
  JUDA_iOS/JUDA.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  JUDA_iOS/JUDA.xcodeproj/xcshareddata/xcschemes/JUDA.xcscheme
  JUDA_iOS/JUDA/Model/Post.swift
  JUDA_iOS/JUDA/Resource/Components/PostCell.swift
  JUDA_iOS/JUDA/View/Mypage/AuthenticatedMypageView.swift
  JUDA_iOS/JUDA/View/Mypage/MypageDetail/ChangeUserNameView.swift
  JUDA_iOS/JUDA/View/Posts/PostDetail/PostDetailView.swift
  JUDA_iOS/JUDA/View/Posts/PostDetail/PostInfo.swift
  JUDA_iOS/JUDA/View/Posts/PostsView.swift
  JUDA_iOS/JUDA/View/Record/RecordView.swift
  JUDA_iOS/JUDA/ViewModel/App/FireStorageService.swift
  JUDA_iOS/JUDA/ViewModel/Drink/FirestoreDrinkService.swift
  JUDA_iOS/JUDA/ViewModel/Posts/FirestorePostService.swift
  JUDA_iOS/JUDA/ViewModel/Posts/PostViewModel.swift
  JUDA_iOS/JUDA/ViewModel/Record/RecordViewModel.swift
Labels: 수정, 🥑 창준, 👻 민재
